<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_alhamdulillah</name>
   <tag></tag>
   <elementGuidId>d281fe06-5ddb-4686-8690-cc5938c217dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[text()='Alhamdulillah!']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[text()='Alhamdulillah!']</value>
      <webElementGuid>5c25d166-ba25-4b40-bedc-be97528c726a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
