<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_KnowAlamiFrom</name>
   <tag></tag>
   <elementGuidId>332b7516-9be9-42d9-9b07-051d71c877e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='registerReferralId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='registerReferralId']</value>
      <webElementGuid>c39f05e5-ffcf-490c-b597-69f7be2c820c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
