<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_email</name>
   <tag></tag>
   <elementGuidId>bbfbf261-02a5-4238-bacd-f129c91fd08c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//*[@id='accounts-list']//child::div//child::div//child::p)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[@id='accounts-list']//child::div//child::div//child::p)[2]</value>
      <webElementGuid>a7c29c2f-9a3e-419e-9171-969300d80c0a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
